export const SET_STATE = 'SET_STATE';
export const RECEIVE_NEW_WORD = 'RECEIVE_NEW_WORD';
export const PLAY_WORD = 'PLAY_WORD';
export const RECORD_USER_AUDIO = 'RECORD_USER_AUDIO';
export const STOP_RECORDING_USER_AUDIO = 'STOP_RECORDING_USER_AUDIO';
export const REQUEST_NEXT_WORD = 'REQUEST_NEXT_WORD';
